/* tslint:disable */
/* eslint-disable */
/**
 * TTX.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreatorShareDto } from './CreatorShareDto';
import {
    CreatorShareDtoFromJSON,
    CreatorShareDtoFromJSONTyped,
    CreatorShareDtoToJSON,
    CreatorShareDtoToJSONTyped,
} from './CreatorShareDto';
import type { CreatorTransactionDto } from './CreatorTransactionDto';
import {
    CreatorTransactionDtoFromJSON,
    CreatorTransactionDtoFromJSONTyped,
    CreatorTransactionDtoToJSON,
    CreatorTransactionDtoToJSONTyped,
} from './CreatorTransactionDto';
import type { StreamStatusDto } from './StreamStatusDto';
import {
    StreamStatusDtoFromJSON,
    StreamStatusDtoFromJSONTyped,
    StreamStatusDtoToJSON,
    StreamStatusDtoToJSONTyped,
} from './StreamStatusDto';
import type { VoteDto } from './VoteDto';
import {
    VoteDtoFromJSON,
    VoteDtoFromJSONTyped,
    VoteDtoToJSON,
    VoteDtoToJSONTyped,
} from './VoteDto';

/**
 * 
 * @export
 * @interface CreatorDto
 */
export interface CreatorDto {
    /**
     * 
     * @type {number}
     * @memberof CreatorDto
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof CreatorDto
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof CreatorDto
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof CreatorDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreatorDto
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof CreatorDto
     */
    twitchId: string;
    /**
     * 
     * @type {string}
     * @memberof CreatorDto
     */
    readonly url: string;
    /**
     * 
     * @type {string}
     * @memberof CreatorDto
     */
    avatarUrl: string;
    /**
     * 
     * @type {string}
     * @memberof CreatorDto
     */
    ticker: string;
    /**
     * 
     * @type {number}
     * @memberof CreatorDto
     */
    value: number;
    /**
     * 
     * @type {StreamStatusDto}
     * @memberof CreatorDto
     */
    streamStatus: StreamStatusDto;
    /**
     * 
     * @type {Array<VoteDto>}
     * @memberof CreatorDto
     */
    history: Array<VoteDto>;
    /**
     * 
     * @type {Array<CreatorTransactionDto>}
     * @memberof CreatorDto
     */
    transactions: Array<CreatorTransactionDto>;
    /**
     * 
     * @type {Array<CreatorShareDto>}
     * @memberof CreatorDto
     */
    shares: Array<CreatorShareDto>;
}

/**
 * Check if a given object implements the CreatorDto interface.
 */
export function instanceOfCreatorDto(value: object): value is CreatorDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('twitchId' in value) || value['twitchId'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('avatarUrl' in value) || value['avatarUrl'] === undefined) return false;
    if (!('ticker' in value) || value['ticker'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('streamStatus' in value) || value['streamStatus'] === undefined) return false;
    if (!('history' in value) || value['history'] === undefined) return false;
    if (!('transactions' in value) || value['transactions'] === undefined) return false;
    if (!('shares' in value) || value['shares'] === undefined) return false;
    return true;
}

export function CreatorDtoFromJSON(json: any): CreatorDto {
    return CreatorDtoFromJSONTyped(json, false);
}

export function CreatorDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatorDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'name': json['name'],
        'slug': json['slug'],
        'twitchId': json['twitch_id'],
        'url': json['url'],
        'avatarUrl': json['avatar_url'],
        'ticker': json['ticker'],
        'value': json['value'],
        'streamStatus': StreamStatusDtoFromJSON(json['stream_status']),
        'history': ((json['history'] as Array<any>).map(VoteDtoFromJSON)),
        'transactions': ((json['transactions'] as Array<any>).map(CreatorTransactionDtoFromJSON)),
        'shares': ((json['shares'] as Array<any>).map(CreatorShareDtoFromJSON)),
    };
}

export function CreatorDtoToJSON(json: any): CreatorDto {
    return CreatorDtoToJSONTyped(json, false);
}

export function CreatorDtoToJSONTyped(value?: Omit<CreatorDto, 'url'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'created_at': ((value['createdAt']).toISOString()),
        'updated_at': ((value['updatedAt']).toISOString()),
        'name': value['name'],
        'slug': value['slug'],
        'twitch_id': value['twitchId'],
        'avatar_url': value['avatarUrl'],
        'ticker': value['ticker'],
        'value': value['value'],
        'stream_status': StreamStatusDtoToJSON(value['streamStatus']),
        'history': ((value['history'] as Array<any>).map(VoteDtoToJSON)),
        'transactions': ((value['transactions'] as Array<any>).map(CreatorTransactionDtoToJSON)),
        'shares': ((value['shares'] as Array<any>).map(CreatorShareDtoToJSON)),
    };
}

