/* tslint:disable */
/* eslint-disable */
/**
 * TTX.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlayerPartialDto } from './PlayerPartialDto';
import {
    PlayerPartialDtoFromJSON,
    PlayerPartialDtoFromJSONTyped,
    PlayerPartialDtoToJSON,
    PlayerPartialDtoToJSONTyped,
} from './PlayerPartialDto';

/**
 * 
 * @export
 * @interface CreatorShareDto
 */
export interface CreatorShareDto {
    /**
     * 
     * @type {PlayerPartialDto}
     * @memberof CreatorShareDto
     */
    player: PlayerPartialDto;
    /**
     * 
     * @type {number}
     * @memberof CreatorShareDto
     */
    quantity: number;
}

/**
 * Check if a given object implements the CreatorShareDto interface.
 */
export function instanceOfCreatorShareDto(value: object): value is CreatorShareDto {
    if (!('player' in value) || value['player'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    return true;
}

export function CreatorShareDtoFromJSON(json: any): CreatorShareDto {
    return CreatorShareDtoFromJSONTyped(json, false);
}

export function CreatorShareDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatorShareDto {
    if (json == null) {
        return json;
    }
    return {
        
        'player': PlayerPartialDtoFromJSON(json['player']),
        'quantity': json['quantity'],
    };
}

export function CreatorShareDtoToJSON(json: any): CreatorShareDto {
    return CreatorShareDtoToJSONTyped(json, false);
}

export function CreatorShareDtoToJSONTyped(value?: CreatorShareDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'player': PlayerPartialDtoToJSON(value['player']),
        'quantity': value['quantity'],
    };
}

