/* tslint:disable */
/* eslint-disable */
/**
 * TTX.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CreatorOrderBy = {
    Name: 'Name',
    Value: 'Value',
    IsLive: 'IsLive'
} as const;
export type CreatorOrderBy = typeof CreatorOrderBy[keyof typeof CreatorOrderBy];


export function instanceOfCreatorOrderBy(value: any): boolean {
    for (const key in CreatorOrderBy) {
        if (Object.prototype.hasOwnProperty.call(CreatorOrderBy, key)) {
            if (CreatorOrderBy[key as keyof typeof CreatorOrderBy] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CreatorOrderByFromJSON(json: any): CreatorOrderBy {
    return CreatorOrderByFromJSONTyped(json, false);
}

export function CreatorOrderByFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatorOrderBy {
    return json as CreatorOrderBy;
}

export function CreatorOrderByToJSON(value?: CreatorOrderBy | null): any {
    return value as any;
}

export function CreatorOrderByToJSONTyped(value: any, ignoreDiscriminator: boolean): CreatorOrderBy {
    return value as CreatorOrderBy;
}

