/* tslint:disable */
/* eslint-disable */
/**
 * TTX.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransactionAction } from './TransactionAction';
import {
    TransactionActionFromJSON,
    TransactionActionFromJSONTyped,
    TransactionActionToJSON,
    TransactionActionToJSONTyped,
} from './TransactionAction';

/**
 * 
 * @export
 * @interface CreateTransactionDto
 */
export interface CreateTransactionDto {
    /**
     * 
     * @type {string}
     * @memberof CreateTransactionDto
     */
    creator: string;
    /**
     * 
     * @type {TransactionAction}
     * @memberof CreateTransactionDto
     */
    action: TransactionAction;
    /**
     * 
     * @type {number}
     * @memberof CreateTransactionDto
     */
    amount: number;
}



/**
 * Check if a given object implements the CreateTransactionDto interface.
 */
export function instanceOfCreateTransactionDto(value: object): value is CreateTransactionDto {
    if (!('creator' in value) || value['creator'] === undefined) return false;
    if (!('action' in value) || value['action'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function CreateTransactionDtoFromJSON(json: any): CreateTransactionDto {
    return CreateTransactionDtoFromJSONTyped(json, false);
}

export function CreateTransactionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTransactionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'creator': json['creator'],
        'action': TransactionActionFromJSON(json['action']),
        'amount': json['amount'],
    };
}

export function CreateTransactionDtoToJSON(json: any): CreateTransactionDto {
    return CreateTransactionDtoToJSONTyped(json, false);
}

export function CreateTransactionDtoToJSONTyped(value?: CreateTransactionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'creator': value['creator'],
        'action': TransactionActionToJSON(value['action']),
        'amount': value['amount'],
    };
}

