/* tslint:disable */
/* eslint-disable */
/**
 * TTX.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Rarity } from './Rarity';
import {
    RarityFromJSON,
    RarityFromJSONTyped,
    RarityToJSON,
    RarityToJSONTyped,
} from './Rarity';
import type { CreatorPartialDto } from './CreatorPartialDto';
import {
    CreatorPartialDtoFromJSON,
    CreatorPartialDtoFromJSONTyped,
    CreatorPartialDtoToJSON,
    CreatorPartialDtoToJSONTyped,
} from './CreatorPartialDto';

/**
 * 
 * @export
 * @interface CreatorRarityDto
 */
export interface CreatorRarityDto {
    /**
     * 
     * @type {CreatorPartialDto}
     * @memberof CreatorRarityDto
     */
    creator: CreatorPartialDto;
    /**
     * 
     * @type {Rarity}
     * @memberof CreatorRarityDto
     */
    rarity: Rarity;
}



/**
 * Check if a given object implements the CreatorRarityDto interface.
 */
export function instanceOfCreatorRarityDto(value: object): value is CreatorRarityDto {
    if (!('creator' in value) || value['creator'] === undefined) return false;
    if (!('rarity' in value) || value['rarity'] === undefined) return false;
    return true;
}

export function CreatorRarityDtoFromJSON(json: any): CreatorRarityDto {
    return CreatorRarityDtoFromJSONTyped(json, false);
}

export function CreatorRarityDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatorRarityDto {
    if (json == null) {
        return json;
    }
    return {
        
        'creator': CreatorPartialDtoFromJSON(json['creator']),
        'rarity': RarityFromJSON(json['rarity']),
    };
}

export function CreatorRarityDtoToJSON(json: any): CreatorRarityDto {
    return CreatorRarityDtoToJSONTyped(json, false);
}

export function CreatorRarityDtoToJSONTyped(value?: CreatorRarityDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'creator': CreatorPartialDtoToJSON(value['creator']),
        'rarity': RarityToJSON(value['rarity']),
    };
}

