/* tslint:disable */
/* eslint-disable */
/**
 * TTX.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlayerPartialDto } from './PlayerPartialDto';
import {
    PlayerPartialDtoFromJSON,
    PlayerPartialDtoFromJSONTyped,
    PlayerPartialDtoToJSON,
    PlayerPartialDtoToJSONTyped,
} from './PlayerPartialDto';
import type { TransactionAction } from './TransactionAction';
import {
    TransactionActionFromJSON,
    TransactionActionFromJSONTyped,
    TransactionActionToJSON,
    TransactionActionToJSONTyped,
} from './TransactionAction';

/**
 * 
 * @export
 * @interface CreatorTransactionDto
 */
export interface CreatorTransactionDto {
    /**
     * 
     * @type {number}
     * @memberof CreatorTransactionDto
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof CreatorTransactionDto
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof CreatorTransactionDto
     */
    updatedAt: Date;
    /**
     * 
     * @type {number}
     * @memberof CreatorTransactionDto
     */
    quantity: number;
    /**
     * 
     * @type {number}
     * @memberof CreatorTransactionDto
     */
    value: number;
    /**
     * 
     * @type {TransactionAction}
     * @memberof CreatorTransactionDto
     */
    action: TransactionAction;
    /**
     * 
     * @type {number}
     * @memberof CreatorTransactionDto
     */
    creatorId: number;
    /**
     * 
     * @type {number}
     * @memberof CreatorTransactionDto
     */
    playerId: number;
    /**
     * 
     * @type {PlayerPartialDto}
     * @memberof CreatorTransactionDto
     */
    player: PlayerPartialDto;
}



/**
 * Check if a given object implements the CreatorTransactionDto interface.
 */
export function instanceOfCreatorTransactionDto(value: object): value is CreatorTransactionDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('action' in value) || value['action'] === undefined) return false;
    if (!('creatorId' in value) || value['creatorId'] === undefined) return false;
    if (!('playerId' in value) || value['playerId'] === undefined) return false;
    if (!('player' in value) || value['player'] === undefined) return false;
    return true;
}

export function CreatorTransactionDtoFromJSON(json: any): CreatorTransactionDto {
    return CreatorTransactionDtoFromJSONTyped(json, false);
}

export function CreatorTransactionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatorTransactionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'quantity': json['quantity'],
        'value': json['value'],
        'action': TransactionActionFromJSON(json['action']),
        'creatorId': json['creator_id'],
        'playerId': json['player_id'],
        'player': PlayerPartialDtoFromJSON(json['player']),
    };
}

export function CreatorTransactionDtoToJSON(json: any): CreatorTransactionDto {
    return CreatorTransactionDtoToJSONTyped(json, false);
}

export function CreatorTransactionDtoToJSONTyped(value?: CreatorTransactionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'created_at': ((value['createdAt']).toISOString()),
        'updated_at': ((value['updatedAt']).toISOString()),
        'quantity': value['quantity'],
        'value': value['value'],
        'action': TransactionActionToJSON(value['action']),
        'creator_id': value['creatorId'],
        'player_id': value['playerId'],
        'player': PlayerPartialDtoToJSON(value['player']),
    };
}

