/* tslint:disable */
/* eslint-disable */
/**
 * TTX.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreatorPartialDto } from './CreatorPartialDto';
import {
    CreatorPartialDtoFromJSON,
    CreatorPartialDtoFromJSONTyped,
    CreatorPartialDtoToJSON,
    CreatorPartialDtoToJSONTyped,
} from './CreatorPartialDto';

/**
 * 
 * @export
 * @interface CreatorPartialDtoPaginationDto
 */
export interface CreatorPartialDtoPaginationDto {
    /**
     * 
     * @type {Array<CreatorPartialDto>}
     * @memberof CreatorPartialDtoPaginationDto
     */
    data: Array<CreatorPartialDto>;
    /**
     * 
     * @type {number}
     * @memberof CreatorPartialDtoPaginationDto
     */
    total: number;
}

/**
 * Check if a given object implements the CreatorPartialDtoPaginationDto interface.
 */
export function instanceOfCreatorPartialDtoPaginationDto(value: object): value is CreatorPartialDtoPaginationDto {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function CreatorPartialDtoPaginationDtoFromJSON(json: any): CreatorPartialDtoPaginationDto {
    return CreatorPartialDtoPaginationDtoFromJSONTyped(json, false);
}

export function CreatorPartialDtoPaginationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatorPartialDtoPaginationDto {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(CreatorPartialDtoFromJSON)),
        'total': json['total'],
    };
}

export function CreatorPartialDtoPaginationDtoToJSON(json: any): CreatorPartialDtoPaginationDto {
    return CreatorPartialDtoPaginationDtoToJSONTyped(json, false);
}

export function CreatorPartialDtoPaginationDtoToJSONTyped(value?: CreatorPartialDtoPaginationDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(CreatorPartialDtoToJSON)),
        'total': value['total'],
    };
}

