/* tslint:disable */
/* eslint-disable */
/**
 * TTX.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TwitchUserDto } from './TwitchUserDto';
import {
    TwitchUserDtoFromJSON,
    TwitchUserDtoFromJSONTyped,
    TwitchUserDtoToJSON,
    TwitchUserDtoToJSONTyped,
} from './TwitchUserDto';

/**
 * 
 * @export
 * @interface DiscordTokenDto
 */
export interface DiscordTokenDto {
    /**
     * 
     * @type {string}
     * @memberof DiscordTokenDto
     */
    accessToken: string;
    /**
     * 
     * @type {string}
     * @memberof DiscordTokenDto
     */
    linkToken: string;
    /**
     * 
     * @type {Array<TwitchUserDto>}
     * @memberof DiscordTokenDto
     */
    readonly twitchUsers: Array<TwitchUserDto>;
}

/**
 * Check if a given object implements the DiscordTokenDto interface.
 */
export function instanceOfDiscordTokenDto(value: object): value is DiscordTokenDto {
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    if (!('linkToken' in value) || value['linkToken'] === undefined) return false;
    if (!('twitchUsers' in value) || value['twitchUsers'] === undefined) return false;
    return true;
}

export function DiscordTokenDtoFromJSON(json: any): DiscordTokenDto {
    return DiscordTokenDtoFromJSONTyped(json, false);
}

export function DiscordTokenDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiscordTokenDto {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['access_token'],
        'linkToken': json['link_token'],
        'twitchUsers': ((json['twitch_users'] as Array<any>).map(TwitchUserDtoFromJSON)),
    };
}

export function DiscordTokenDtoToJSON(json: any): DiscordTokenDto {
    return DiscordTokenDtoToJSONTyped(json, false);
}

export function DiscordTokenDtoToJSONTyped(value?: Omit<DiscordTokenDto, 'twitch_users'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_token': value['accessToken'],
        'link_token': value['linkToken'],
    };
}

