/* tslint:disable */
/* eslint-disable */
/**
 * TTX.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LinkDiscordTwitchDto
 */
export interface LinkDiscordTwitchDto {
    /**
     * 
     * @type {string}
     * @memberof LinkDiscordTwitchDto
     */
    accessToken: string;
    /**
     * 
     * @type {string}
     * @memberof LinkDiscordTwitchDto
     */
    twitchId: string;
}

/**
 * Check if a given object implements the LinkDiscordTwitchDto interface.
 */
export function instanceOfLinkDiscordTwitchDto(value: object): value is LinkDiscordTwitchDto {
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    if (!('twitchId' in value) || value['twitchId'] === undefined) return false;
    return true;
}

export function LinkDiscordTwitchDtoFromJSON(json: any): LinkDiscordTwitchDto {
    return LinkDiscordTwitchDtoFromJSONTyped(json, false);
}

export function LinkDiscordTwitchDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkDiscordTwitchDto {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['access_token'],
        'twitchId': json['twitch_id'],
    };
}

export function LinkDiscordTwitchDtoToJSON(json: any): LinkDiscordTwitchDto {
    return LinkDiscordTwitchDtoToJSONTyped(json, false);
}

export function LinkDiscordTwitchDtoToJSONTyped(value?: LinkDiscordTwitchDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_token': value['accessToken'],
        'twitch_id': value['twitchId'],
    };
}

