/* tslint:disable */
/* eslint-disable */
/**
 * TTX.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PlayerOrderBy = {
    Name: 'Name',
    Credits: 'Credits',
    Portfolio: 'Portfolio'
} as const;
export type PlayerOrderBy = typeof PlayerOrderBy[keyof typeof PlayerOrderBy];


export function instanceOfPlayerOrderBy(value: any): boolean {
    for (const key in PlayerOrderBy) {
        if (Object.prototype.hasOwnProperty.call(PlayerOrderBy, key)) {
            if (PlayerOrderBy[key as keyof typeof PlayerOrderBy] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PlayerOrderByFromJSON(json: any): PlayerOrderBy {
    return PlayerOrderByFromJSONTyped(json, false);
}

export function PlayerOrderByFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayerOrderBy {
    return json as PlayerOrderBy;
}

export function PlayerOrderByToJSON(value?: PlayerOrderBy | null): any {
    return value as any;
}

export function PlayerOrderByToJSONTyped(value: any, ignoreDiscriminator: boolean): PlayerOrderBy {
    return value as PlayerOrderBy;
}

