/* tslint:disable */
/* eslint-disable */
/**
 * TTX.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PlayerType = {
    User: 'User',
    Admin: 'Admin'
} as const;
export type PlayerType = typeof PlayerType[keyof typeof PlayerType];


export function instanceOfPlayerType(value: any): boolean {
    for (const key in PlayerType) {
        if (Object.prototype.hasOwnProperty.call(PlayerType, key)) {
            if (PlayerType[key as keyof typeof PlayerType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PlayerTypeFromJSON(json: any): PlayerType {
    return PlayerTypeFromJSONTyped(json, false);
}

export function PlayerTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayerType {
    return json as PlayerType;
}

export function PlayerTypeToJSON(value?: PlayerType | null): any {
    return value as any;
}

export function PlayerTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): PlayerType {
    return value as PlayerType;
}

