/* tslint:disable */
/* eslint-disable */
/**
 * TTX.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreatorPartialDto } from './CreatorPartialDto';
import {
    CreatorPartialDtoFromJSON,
    CreatorPartialDtoFromJSONTyped,
    CreatorPartialDtoToJSON,
    CreatorPartialDtoToJSONTyped,
} from './CreatorPartialDto';

/**
 * 
 * @export
 * @interface PlayerShareDto
 */
export interface PlayerShareDto {
    /**
     * 
     * @type {CreatorPartialDto}
     * @memberof PlayerShareDto
     */
    creator: CreatorPartialDto;
    /**
     * 
     * @type {number}
     * @memberof PlayerShareDto
     */
    quantity: number;
}

/**
 * Check if a given object implements the PlayerShareDto interface.
 */
export function instanceOfPlayerShareDto(value: object): value is PlayerShareDto {
    if (!('creator' in value) || value['creator'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    return true;
}

export function PlayerShareDtoFromJSON(json: any): PlayerShareDto {
    return PlayerShareDtoFromJSONTyped(json, false);
}

export function PlayerShareDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayerShareDto {
    if (json == null) {
        return json;
    }
    return {
        
        'creator': CreatorPartialDtoFromJSON(json['creator']),
        'quantity': json['quantity'],
    };
}

export function PlayerShareDtoToJSON(json: any): PlayerShareDto {
    return PlayerShareDtoToJSONTyped(json, false);
}

export function PlayerShareDtoToJSONTyped(value?: PlayerShareDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'creator': CreatorPartialDtoToJSON(value['creator']),
        'quantity': value['quantity'],
    };
}

