/* tslint:disable */
/* eslint-disable */
/**
 * TTX.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreatorPartialDto } from './CreatorPartialDto';
import {
    CreatorPartialDtoFromJSON,
    CreatorPartialDtoFromJSONTyped,
    CreatorPartialDtoToJSON,
    CreatorPartialDtoToJSONTyped,
} from './CreatorPartialDto';
import type { TransactionAction } from './TransactionAction';
import {
    TransactionActionFromJSON,
    TransactionActionFromJSONTyped,
    TransactionActionToJSON,
    TransactionActionToJSONTyped,
} from './TransactionAction';

/**
 * 
 * @export
 * @interface PlayerTransactionDto
 */
export interface PlayerTransactionDto {
    /**
     * 
     * @type {number}
     * @memberof PlayerTransactionDto
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof PlayerTransactionDto
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof PlayerTransactionDto
     */
    updatedAt: Date;
    /**
     * 
     * @type {number}
     * @memberof PlayerTransactionDto
     */
    quantity: number;
    /**
     * 
     * @type {number}
     * @memberof PlayerTransactionDto
     */
    value: number;
    /**
     * 
     * @type {TransactionAction}
     * @memberof PlayerTransactionDto
     */
    action: TransactionAction;
    /**
     * 
     * @type {number}
     * @memberof PlayerTransactionDto
     */
    creatorId: number;
    /**
     * 
     * @type {number}
     * @memberof PlayerTransactionDto
     */
    playerId: number;
    /**
     * 
     * @type {CreatorPartialDto}
     * @memberof PlayerTransactionDto
     */
    creator: CreatorPartialDto;
}



/**
 * Check if a given object implements the PlayerTransactionDto interface.
 */
export function instanceOfPlayerTransactionDto(value: object): value is PlayerTransactionDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('action' in value) || value['action'] === undefined) return false;
    if (!('creatorId' in value) || value['creatorId'] === undefined) return false;
    if (!('playerId' in value) || value['playerId'] === undefined) return false;
    if (!('creator' in value) || value['creator'] === undefined) return false;
    return true;
}

export function PlayerTransactionDtoFromJSON(json: any): PlayerTransactionDto {
    return PlayerTransactionDtoFromJSONTyped(json, false);
}

export function PlayerTransactionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayerTransactionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'quantity': json['quantity'],
        'value': json['value'],
        'action': TransactionActionFromJSON(json['action']),
        'creatorId': json['creator_id'],
        'playerId': json['player_id'],
        'creator': CreatorPartialDtoFromJSON(json['creator']),
    };
}

export function PlayerTransactionDtoToJSON(json: any): PlayerTransactionDto {
    return PlayerTransactionDtoToJSONTyped(json, false);
}

export function PlayerTransactionDtoToJSONTyped(value?: PlayerTransactionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'created_at': ((value['createdAt']).toISOString()),
        'updated_at': ((value['updatedAt']).toISOString()),
        'quantity': value['quantity'],
        'value': value['value'],
        'action': TransactionActionToJSON(value['action']),
        'creator_id': value['creatorId'],
        'player_id': value['playerId'],
        'creator': CreatorPartialDtoToJSON(value['creator']),
    };
}

