/* tslint:disable */
/* eslint-disable */
/**
 * TTX.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Rarity = {
    Pennies: 'Pennies',
    Common: 'Common',
    Rare: 'Rare',
    Epic: 'Epic'
} as const;
export type Rarity = typeof Rarity[keyof typeof Rarity];


export function instanceOfRarity(value: any): boolean {
    for (const key in Rarity) {
        if (Object.prototype.hasOwnProperty.call(Rarity, key)) {
            if (Rarity[key as keyof typeof Rarity] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RarityFromJSON(json: any): Rarity {
    return RarityFromJSONTyped(json, false);
}

export function RarityFromJSONTyped(json: any, ignoreDiscriminator: boolean): Rarity {
    return json as Rarity;
}

export function RarityToJSON(value?: Rarity | null): any {
    return value as any;
}

export function RarityToJSONTyped(value: any, ignoreDiscriminator: boolean): Rarity {
    return value as Rarity;
}

