/* tslint:disable */
/* eslint-disable */
/**
 * TTX.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StreamStatusDto
 */
export interface StreamStatusDto {
    /**
     * 
     * @type {boolean}
     * @memberof StreamStatusDto
     */
    isLive: boolean;
    /**
     * 
     * @type {Date}
     * @memberof StreamStatusDto
     */
    startedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof StreamStatusDto
     */
    endedAt?: Date | null;
}

/**
 * Check if a given object implements the StreamStatusDto interface.
 */
export function instanceOfStreamStatusDto(value: object): value is StreamStatusDto {
    if (!('isLive' in value) || value['isLive'] === undefined) return false;
    return true;
}

export function StreamStatusDtoFromJSON(json: any): StreamStatusDto {
    return StreamStatusDtoFromJSONTyped(json, false);
}

export function StreamStatusDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): StreamStatusDto {
    if (json == null) {
        return json;
    }
    return {
        
        'isLive': json['is_live'],
        'startedAt': json['started_at'] == null ? undefined : (new Date(json['started_at'])),
        'endedAt': json['ended_at'] == null ? undefined : (new Date(json['ended_at'])),
    };
}

export function StreamStatusDtoToJSON(json: any): StreamStatusDto {
    return StreamStatusDtoToJSONTyped(json, false);
}

export function StreamStatusDtoToJSONTyped(value?: StreamStatusDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'is_live': value['isLive'],
        'started_at': value['startedAt'] == null ? undefined : ((value['startedAt'] as any).toISOString()),
        'ended_at': value['endedAt'] == null ? undefined : ((value['endedAt'] as any).toISOString()),
    };
}

