/* tslint:disable */
/* eslint-disable */
/**
 * TTX.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TimeStep = {
    Minute: 'Minute',
    FiveMinute: 'FiveMinute',
    FifteenMinute: 'FifteenMinute',
    ThirtyMinute: 'ThirtyMinute',
    Hour: 'Hour',
    Day: 'Day',
    Week: 'Week',
    Month: 'Month'
} as const;
export type TimeStep = typeof TimeStep[keyof typeof TimeStep];


export function instanceOfTimeStep(value: any): boolean {
    for (const key in TimeStep) {
        if (Object.prototype.hasOwnProperty.call(TimeStep, key)) {
            if (TimeStep[key as keyof typeof TimeStep] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TimeStepFromJSON(json: any): TimeStep {
    return TimeStepFromJSONTyped(json, false);
}

export function TimeStepFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeStep {
    return json as TimeStep;
}

export function TimeStepToJSON(value?: TimeStep | null): any {
    return value as any;
}

export function TimeStepToJSONTyped(value: any, ignoreDiscriminator: boolean): TimeStep {
    return value as TimeStep;
}

