/* tslint:disable */
/* eslint-disable */
/**
 * TTX.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TransactionAction = {
    Buy: 'Buy',
    Sell: 'Sell',
    Open: 'Open'
} as const;
export type TransactionAction = typeof TransactionAction[keyof typeof TransactionAction];


export function instanceOfTransactionAction(value: any): boolean {
    for (const key in TransactionAction) {
        if (Object.prototype.hasOwnProperty.call(TransactionAction, key)) {
            if (TransactionAction[key as keyof typeof TransactionAction] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TransactionActionFromJSON(json: any): TransactionAction {
    return TransactionActionFromJSONTyped(json, false);
}

export function TransactionActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionAction {
    return json as TransactionAction;
}

export function TransactionActionToJSON(value?: TransactionAction | null): any {
    return value as any;
}

export function TransactionActionToJSONTyped(value: any, ignoreDiscriminator: boolean): TransactionAction {
    return value as TransactionAction;
}

