/* tslint:disable */
/* eslint-disable */
/**
 * TTX.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VoteDto
 */
export interface VoteDto {
    /**
     * 
     * @type {number}
     * @memberof VoteDto
     */
    creatorId: number;
    /**
     * 
     * @type {number}
     * @memberof VoteDto
     */
    value: number;
    /**
     * 
     * @type {Date}
     * @memberof VoteDto
     */
    time: Date;
}

/**
 * Check if a given object implements the VoteDto interface.
 */
export function instanceOfVoteDto(value: object): value is VoteDto {
    if (!('creatorId' in value) || value['creatorId'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('time' in value) || value['time'] === undefined) return false;
    return true;
}

export function VoteDtoFromJSON(json: any): VoteDto {
    return VoteDtoFromJSONTyped(json, false);
}

export function VoteDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VoteDto {
    if (json == null) {
        return json;
    }
    return {
        
        'creatorId': json['creator_id'],
        'value': json['value'],
        'time': (new Date(json['time'])),
    };
}

export function VoteDtoToJSON(json: any): VoteDto {
    return VoteDtoToJSONTyped(json, false);
}

export function VoteDtoToJSONTyped(value?: VoteDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'creator_id': value['creatorId'],
        'value': value['value'],
        'time': ((value['time']).toISOString()),
    };
}

